[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npx tsc -p tsconfig.mcp.json"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
